# 1. Imagen base de Node.js
FROM node:16

# 2. Metadatos de la imagen
LABEL maintainer="Jhoinermartinez243@gmail.com"

# 3. Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# 4. Copiar package.json y package-lock.json
COPY package.json package-lock.json /app/

# 5. Instalar dependencias
RUN npm install

# 6. Copiar el resto del código de la aplicación
COPY . /app/

# 7. Copiar el archivo de claves de Firebase al contenedor
COPY . C:\Users\jhoip\Desktop\service-account-file.json

# 8. Exponer el puerto 3000
EXPOSE 3000

# 9. Definir el comando para iniciar la aplicación
CMD ["npm", "start"]
